export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headline: 'Unlimited Transactions with zero fees',
    description: 'Get access to our exclusive app that allows you to send unlimited transactions without getting charged any fees.',
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../../images/png-1.png'),
    alt: 'Money',
    dark: true,
    primary: true,
    darkText: false,
}

export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Unlimited Access',
    headline: 'Unlimited Transactions with zero fees',
    description: 'We havew you covered no matter where you are located. All you need is connection to the Internet and mobile phone or computer.',
    buttonLabel: 'Learn more',
    imgStart: true,
    img: require('../../images/png-2.png'),
    alt: 'Stocks',
    dark: false,
    primary: false,
    darkText: true,
}

export const homeObjThree = {
    id: 'signup',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Join our team',
    headline: 'Creating an account is extremely easy.',
    description: 'Get everything set up and ready in 10 minutes. All you need to do is add your information and you are ready to go.',
    buttonLabel: 'Start now',
    imgStart: false,
    img: require('../../images/png-1.png'),
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
}